### ISSUE TITLE
chart-operator locks if helm chart can not create all pods

### ISSUE THREAD

**Issue by r7vme** [giantswarm/chart-operator#73]
I had a case, when cluster has only one worker and chart-operator stuck on installing nginx-ingress-controller chart, because two of three pods were pending.
```
{"caller":"github.com/giantswarm/chart-operator/service/controller/v1/resource/chart/create.go:24","event":"update","function":"ApplyCreateChange","level":"debug","message":"creating chart kubernetes-nginx-ingress-controller-chart","object":"/apis/core.giantswarm.io/v1alpha1/namespaces/giantswarm/chartconfigs/kubernetes-nginx-ingress-controller-chart","resource":"chartv1","time":"2018-06-13T13:53:32.589055+00:00"}
```

I assume we need to change some `helm install` flags to not wait until all pods will be runnning.

**Comment by r7vme** [comment]
cc: @fgimenez @rossf7

**Comment by rossf7** [comment]
Damnit, yes we need to be able to pass values to Helm charts. This is because in k8scloudconfig we have templating for the number of workers.

See https://github.com/giantswarm/giantswarm/issues/3389

@puja108 I think we need to tackle this next on Managed Services.

**Comment by r7vme** [comment]
Is it possible to install chart asynchronously?

One of the customers expects quick provisioning of the cluster services and additional saved 10 minutes would be great boost.

**Comment by puja108** [comment]
yes, apart from the values support we are building we should look into making chart installs non-blocking, which also sounds like the more k8s way, the job of chart-operator is just sending it over to the K8s API through Tiller, then it's the job of K8s to make that desired state also the current state. Reconcilliation of chart-operator should be based on what k8s knows as desired state, and reconciliation of current state is k8s master territory.

**Comment by rossf7** [comment]
Yes we should proceed to the next chart. I think part of the problem is we're waiting when installing the chart.

https://github.com/giantswarm/chart-operator/blob/2076511f3f54d3baabbfa6499617b5a483690765/service/controller/v1/resource/chart/create.go#L57

@fgimenez @indyfree Do you know why we did it this way?

**Comment by fgimenez** [comment]
Sure, we should remove it to proceed. I don't remember exactly the reason for that `InstallWait`, it was added in this commit https://github.com/giantswarm/chart-operator/pull/51/commits/f8c80a3b0b45e9d89e03dbf27cff3867b852addb, and was added both for the test setup and for the production code. My guess is that the code was copy&pasted, for the test setup we need `InstallWait` in the call to `helmClient.InstallFromTarball` for installing the CNR server but not while creating charts in in normal  operator work.

I can prepare a PR for removing it.

**Comment by rossf7** [comment]
Thanks! Yes I think removing it is the right call.

**Comment by fgimenez** [comment]
Done in https://github.com/giantswarm/chart-operator/pull/79
